// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6Q_S4Fm6zqlS6W94BXOu5sRIfoq5mOo',
    appId: '1:239169882171:web:8c1c99875ebe9aa020f41e',
    messagingSenderId: '239169882171',
    projectId: 'scalendar-e368d',
    authDomain: 'scalendar-e368d.firebaseapp.com',
    storageBucket: 'scalendar-e368d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_EhVDc5bp1tUjK25qWFBBT5qCR6Pfd4',
    appId: '1:239169882171:android:6cb06e007adf6e5020f41e',
    messagingSenderId: '239169882171',
    projectId: 'scalendar-e368d',
    storageBucket: 'scalendar-e368d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADQHBP5EVAw02pbzwN29uZj-YhrT_Wg6E',
    appId: '1:239169882171:ios:bd1de517af665bc220f41e',
    messagingSenderId: '239169882171',
    projectId: 'scalendar-e368d',
    storageBucket: 'scalendar-e368d.firebasestorage.app',
    iosBundleId: 'com.example.myUrlSummarizerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADQHBP5EVAw02pbzwN29uZj-YhrT_Wg6E',
    appId: '1:239169882171:ios:bd1de517af665bc220f41e',
    messagingSenderId: '239169882171',
    projectId: 'scalendar-e368d',
    storageBucket: 'scalendar-e368d.firebasestorage.app',
    iosBundleId: 'com.example.myUrlSummarizerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy6Q_S4Fm6zqlS6W94BXOu5sRIfoq5mOo',
    appId: '1:239169882171:web:3d3206d44b8aca2320f41e',
    messagingSenderId: '239169882171',
    projectId: 'scalendar-e368d',
    authDomain: 'scalendar-e368d.firebaseapp.com',
    storageBucket: 'scalendar-e368d.firebasestorage.app',
  );
}
